// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using mealFinderDotNet.Data;

#nullable disable

namespace mealFinderDotNet.Migrations
{
    [DbContext(typeof(TaBaseContext))]
    partial class TaBaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            // Table Favoris
            modelBuilder.Entity("mealFinderDotNet.Models.Favori", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                b.Property<int>("IdRecetteAPI")
                    .HasColumnType("int");

                b.Property<int>("UtilisateurId")
                    .HasColumnType("int");

                b.HasKey("Id");

                b.ToTable("Favoris");
            });

            // Table Recettes
            modelBuilder.Entity("mealFinderDotNet.Models.Recette", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                b.Property<string>("Image")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.PrimitiveCollection<string>("Ingredients")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Instructions")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<int>("ReadyInMinutes")
                    .HasColumnType("int");

                b.Property<int>("Servings")
                    .HasColumnType("int");

                b.Property<string>("Titre")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.HasKey("Id");

                b.ToTable("Recettes");
            });

            // Table Utilisateurs
            modelBuilder.Entity("mealFinderDotNet.Models.Utilisateur", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                b.Property<DateTime>("DateInscription")
                    .HasColumnType("datetime2");

                b.Property<string>("Email")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("MotDePasse")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Nom")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Prenom")
                    .HasColumnType("nvarchar(max)");

                b.HasKey("Id");

                b.ToTable("Utilisateurs");
            });
#pragma warning restore 612, 618
        }
    }
}
